[workspace]
members = [
    "rusteron-code-gen",
    "rusteron-archive",
    "rusteron-media-driver",
    "rusteron-client",
]
resolver = "2"

[workspace.dependencies]
ctrlc = "3.4"
bindgen = "0.70"
cmake = "0.1"
dunce = "1.0"
pkg-config = "0.3"
syn = { version = "2.0", features = ["full"] }
proc-macro2 = "1.0"
quote = "1.0"
itertools = "0.13"
num-format = "0.4"
hdrhistogram = "7.5"
zerocopy = { version = "0.8", features = ["derive", "simd", "alloc"] }
criterion = "0.5"

[release]
publish = true
workspace = true
consolidate_commits = true
auto_publish = true
push = true
tag = true
dependency_version = "update"


[profile.release]
#opt-level = 3
debug = true
debug-assertions = false
overflow-checks = false
lto = "thin"
