apiVersion: v1
kind: Pod
metadata:
  name: dummy-example
spec:
  containers:
    - name: aeron-media-driver
      image: aeron-media-driver:latest
      volumeMounts:
        - name: shared-data
          mountPath: /data
      env:
        - name: "aeron.threading.mode"
          value: "DEDICATED"
        - name: "aeron.sender.idle.strategy"
          value: "backoff"
        - name: "aeron.receiver.idle.strategy"
          value: "backoff"
        - name: "aeron.conductor.idle.strategy"
          value: "backoff"
        - name: "aeron.archive.dir"
          value: "/data"
        - name: "aeron.archive.control.channel"
          value: "aeron:udp?endpoint=localhost:8010"
        - name: "aeron.archive.control.response.channel"
          value: "aeron:udp?endpoint=localhost:8011"
        - name: "aeron.archive.replication.channel"
          value: "aeron:udp?endpoint=localhost:8012"

    - name: ticker-writer
      image: rusteron-dummy-example:latest
      args: [ "ticker_writer" ]
      volumeMounts:
        - name: shared-data
          mountPath: /data
      env:
        - name: "AERON_THREADING_MODE"
          value: "DEDICATED"
        - name: "AERON_ARCHIVE_CONTROL_CHANNEL"
          value: "aeron:udp?endpoint=localhost:8010"
        - name: "AERON_ARCHIVE_CONTROL_RESPONSE_CHANNEL"
          value: "aeron:udp?endpoint=localhost:8011"
        - name: "AERON_ARCHIVE_REPLICATION_CHANNEL"
          value: "aeron:udp?endpoint=localhost:8012"

    - name: ticker-reader
      image: rusteron-dummy-example:latest
      args: [ "ticker_reader" ]
      volumeMounts:
        - name: shared-data
          mountPath: /data
      env:
        - name: "AERON_THREADING_MODE"
          value: "DEDICATED"
        - name: "AERON_ARCHIVE_CONTROL_CHANNEL"
          value: "aeron:udp?endpoint=localhost:8010"
        - name: "AERON_ARCHIVE_CONTROL_RESPONSE_CHANNEL"
          value: "aeron:udp?endpoint=localhost:8011"
        - name: "AERON_ARCHIVE_REPLICATION_CHANNEL"
          value: "aeron:udp?endpoint=localhost:8012"

  volumes:
    - name: shared-data
      emptyDir: {}
    # don't need to do shm as pod shared /dev/shm anyway
