[package]
name = "rusteron-media-driver"
version = "0.1.132"
edition = "2021"
authors = ["Mo Imran <mimran1980@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/mimran1980/rusteron"
homepage = "https://github.com/mimran1980/rusteron"
keywords = ["aeron", "low-latency", "media-driver", "aeron-c-bindings", "networking"]
categories = ["network-programming"]
documentation = "https://mimran1980.github.io/rusteron/rusteron_media_driver/index.html"
description = "Implements the Aeron Media Driver, a core component for managing messaging between producers and consumers. It uses the Aeron C bindings from aeron-driver module."
readme = "README.md"

exclude = [
    "aeron/.gradle/**",
    "aeron/buildSrc/.gradle/**",
    "aeron/build/**",
    "aeron/aeron-agent/build/**",
    "aeron/aeron-all/build/**",
    "aeron/aeron-annotations/build/**",
    "aeron/aeron-archive/build/**",
    "aeron/aeron-client/build/**",
    "aeron/aeron-cluster/build/**",
    "aeron/aeron-driver/build/**",
    "aeron/aeron-samples/build/**",
    "aeron/aeron-system-tests/build/**",
    "aeron/aeron-test-support/build/**",
    "aeron/buildSrc/build/**",
]

[dependencies]
ctrlc = { workspace = true }
log = { workspace = true}
regex = { workspace = true}

[dev-dependencies]
env_logger = "0.11"

[build-dependencies]
bindgen = {  workspace = true }
cmake = {  workspace = true }
dunce = {  workspace = true }
pkg-config = {  workspace = true }
proc-macro2 = {  workspace = true }
rusteron-code-gen = { workspace = true }
log = { workspace = true}
regex = { workspace = true}
walkdir = { workspace = true}
reqwest = {workspace = true}
flate2 = {workspace = true}
tar    = {workspace = true}

[features]
# using static as different modules have different versions of aeron which don't seem to play nicely
default=[]
static=[]
# logs the backtrace on each AeronCError
backtrace = []
extra-logging = []
precompile = []

[[bin]]
name = "media_driver"
path = "src/bin/media_driver.rs"

[package.metadata.docs.rs]
features = ["static", "precompile"]
default-target = "x86_64-apple-darwin"
